# cs.toml - v10.0.219.2
[addon]
appDesc = '''Stáhnout videa z webu.'''
restore_purchase_button = '''Obnova nákupu'''
get_premium_button = '''Získat prémium'''
back = '''Zpět'''
waiting_for_media = '''Čekám na média...'''
nomedia_title = '''Nevidíte média která hledáte?'''
nomedia_description = '''Spusťte video (a přeskočte případné reklamy) abyste pomohli s detekcí. Nebo nahlaste chbějící média.'''
nomedia_reload_button = '''Vynutit detekci'''
nomedia_reload_button_tooltip = '''Vynutí si znovunačtení stránky (smaže cookies)'''
show_nomedia_button = '''Žádné video?'''
show_nomedia_button_tooltip = '''Klikněte zde, pokud nemůžete najít své video'''
setting_button_tooltip = '''Nastavení'''
history_button_tooltip = '''Zobrazit historii stahování'''
show_all_history_button = '''ukaž vše'''
complete_title = '''Dokončeno'''
hide_complete_button = '''zkrýt'''
translate_button_tooltip = '''Pomozte s překladem VDH'''
open_source_tab_button_tooltip = '''Panel Open source'''
retry_download_button_tooltip = '''Obnovit stahování'''
delete_file_button_tooltip = '''Smazat soubor'''
download_directory_button_tooltip = '''Ukáže složku stahování'''
clear_downloaded_tooltip = '''Vyčistí dokončená stahování'''
show_in_popup_button_tooltip = '''Ukázat ve vyskakovacím okně'''
show_in_sidebar_button_tooltip = '''Ukázat v postranní liště'''
video_not_playing_button_tooltip = '''Video nehraje?'''
play = '''Přehrát'''
warn_drm_tooltip = '''Zjištěno DRM'''
version_title = '''Verze'''
account_title = '''Účet'''
one_hundred_downloads_title = '''Stáhli jste 100 videí!'''
leave_review_description = '''Doufáme, že se vám Vide Download Helper líbí :) Nevadilo by vám napsat nám pěkné hodnocení na stránce rozšíření?'''
leave_review_button = '''Zanechte nám hodnocení'''
account_status = '''Status'''
account_status_premium = '''Prémium ($1)'''
free_account = '''Užívání zdarma'''
copy_to_clipboard = '''Zkopírovat informaci do schránky'''
my_account_button = '''Můj účet'''
download_title = '''Stahování'''
show_notification = '''Zobraz upozornění až bude stahování hotovo'''
max_parallel_downloads = '''Maximum současných stahování'''
change_download_directory = '''Změnit cílovou složku'''
saveas_detected_warning = '''Zjistili jsme, že váš prohlížeč otevírá „Save As“ dialog jakmile je stahování dokončeno. Doporučujeme tuto možnost vypnout v nastavení prohlížeče.'''
change_saveas_setting = '''Změnit nastavení'''
private_browsing_title = '''Spokromé prohlížení'''
private_browsing_warning = '''Vide Download Helper není povolen v Soukromých/Inkognito oknech. Tuto možnost musíte zapnout ručně (toto není vyžadováno).'''
private_browsing_notifications = '''Ukazovat upozornění pro soukromé stahování'''
private_browsing_button = '''Změnit nastavení pro soukromé prohlížení'''
throttle_youtube = '''Zpomalit YouTube (pomaleší stahování, ale menší riziko zablokování)'''
prefer_original_audio = '''Upřednostnit originální audio'''
prefer_hls = '''Upřednostnit HLS'''
settings_history_title = '''Historie'''
transient_history_description = '''Ukaž dokončená stahování v panelu'''
history_limit = '''Zapomeň historii stahování po X dnech'''
appearance_title = '''Vzhled'''
theme_title = '''Téma'''
theme_light = '''světlé'''
theme_dark = '''tmavé'''
theme_system = '''systém'''
popup_size_title = '''Velikost okna'''
popup_size_small = '''Malé'''
popup_size_medium = '''Střední'''
popup_size_big = '''Velké'''
panel_position_title = '''Umístění panelu'''
use_popup = '''Ukázat ve vyskakovacím okně'''
use_sidebar = '''Ukázat v počním panelu'''
behavior_title = '''Chování'''
controls_title = '''Ovládání'''
show_in_context_menu = '''Přístup k příkazům přes pravý klik na stránce'''
restart_addon = '''Znovunačtení rozšíření'''
reset_settings = '''Reset nastavení'''
prefer_highest_quality = '''Vyber nejvyšší kvalitu místo 1080p jako výchozí (pomalejší stahování, vyšší kvalita).'''
prefer_mkv = '''Stahuj jako MKV, pokud možno'''
preview_mode_title = '''Náhled média'''
preview_mode_none = '''Vypnuto'''
preview_mode_video = '''Krátká video ukázka'''
preview_mode_image = '''Obrázek'''
history_title = '''Historie stahování'''
history_warning = '''Nezaznamenáváme historii vašich stahování. Chcete aby si Vide Download Helper pamatoval co jste stahovali?'''
history_warning_2 = '''Bez obav, vše zústává ve vašem počítači. My ctíme vaše soukromí.'''
enable_history = '''Zapnout historii'''
clear_history = '''Vyčistit historii'''
disable_history = '''Nezaznamenávej moji činnost'''
no_downloads_yet = '''Zatím nic.'''
download_failed = '''Stahování selhalo'''
download_failed_description = '''Žel, nezvládli jsme stáhnou toto konkrétní médium. Snažíme se podporovat tolik webů, kolik jen jde, proto by nám pomohlo, kdybyste nahlásili tuhle chybu (je to anonymní!).'''
download_interrupted = '''Stahování přerušeno'''
download_interrupted_description = '''Dařilo se nám stahovat váš soubor, ale nastaly potíže se sítí, takže soubor může být kratší, než čekáte. Snažíme se podporovat tolik webů, kolik jen jde, proto by nám pomohlo, kdybyste nahlásili tuhle chybu (je to anonymní!).'''
download_with_drm_failed_description = '''Něco bylo špatně, a my maslíme, že video má DRM. Videa s DRM nepodporujeme.'''
no_youtube = '''Stahování z youtube není dovoleno'''
no_youtube_description = '''Naneštěstí Web obchod Chromu nepovoluje rozšíření, která umožňují stahovat videa z YouTube, takže tuto funkci nemůžeme zahrnout do Chrome verze tohoto rozšíření.'''
no_youtube_description_2 = '''Použijte prosím Firefox nebo Microsoft Edge'''
premium_required = '''Vyžadován status Premium'''
premium_yt_required_description = '''Bez statusu Premium může být download z YouTube proveden až za dvě hodiny po tom předchozím.'''
premium_required_description = '''Bez statutu Premium může být provedeno HLS nebo MPD stahování až dvě hodiny po tom předchozím.'''
youtube_too_many_downloads = '''Jejda, YouTube vypadá zablokovaně'''
youtube_too_many_downloads_description = '''YouTube občas omezuje kolik videí může být požadováno. S tím žel nic nenaděláme. Zkuste to později.'''
stop = '''Stop'''
cancel = '''Zrušit'''
copy_url = '''Zkopíruj URL'''
always_copy_url = '''Vždy kopíruj URL'''
download_button = '''Stáhnout'''
download_as_button_and_menu = '''Stáhnout jako...'''
rename_short = '''Přejmenovat'''
always_download_as_menu = '''Vždy stahovat jako...'''
download_audio_button = '''Zvuk'''
download_audio_and_video_menu = '''Stáhni zvuk i video'''
download_audio_only_menu = '''Stáhni zvuk'''
audio_only_for_this_website = '''Pro tento web stahuj vždy jen zvuk'''
details = '''Podrobnosti'''
more_settings = '''Další nastavení'''
report = '''Nahlásit'''
reporting = '''Hlásím...'''
reported = '''Nahlášeno, děkujeme!'''
not_playing_title = '''Video nehraje?'''
not_playing_broken_title = '''Nefunguje zvuk nebo video?'''
not_playing_broken_description = '''Nahlaste selhávající média. Uděláme co bude v našich silách abychom zjistili proč (pošleme si URL videa anonymně - nesledujeme vás!)'''
not_playing_broken_solution_title = '''Zkuste moderní video přehrávač'''
not_playing_broken_solution_windows_1 = '''Doporučujeme VLC:'''
not_playing_broken_solution_mac_1 = '''Doporučujeme IINA:'''
not_playing_broken_solution_2 = '''je moderní, bezpečný a Open Source.'''
not_playing_default_player = '''Ujistěte se, že váš video přehrávač je nastaven jako výchozí systémový přehrávač videí.'''
not_playing_default_player_solution_windows = '''Ve Windows 11 otevřete „Nastavení“, vpravo klikněte na „Aplikace“ a najděte a klikněte vlevo na „Výchozí aplikace“. Tam vyhledejte svůj přehrávač a nastavte jej jako výchozí pro požadované přípony souborů.'''
not_playing_default_player_solution_mac = '''Otevřete složku stahování pravým klikem na video soubor. Klikněte na „Informace“ a v sekci „Otevřít pomocí“ zvolte IINA. Klikněte na tlačítko „Změnit vše“.'''

[web]
back = '''Zpět'''
header_help = '''Nápověda'''
header_community = '''Komunita'''
activate_title = '''Aktivace'''
activate_pending = '''Čekám...'''
activate_success = '''Úspěch'''
activate_error = '''Chyba'''
activate_no_addon_found = '''Přídavná aplikace nenalezena. Máte ji nainstalovánu?'''
activate_no_method_found = '''Nebyla nalezena žádná metoda.'''
activate_help_me = '''Pomoz mi.'''
issue_title = '''Obnova nákupu'''
issue_submit = '''Odeslat'''
issue_thank_you = '''Děkujeme'''
issue_enter_email = '''Pro obnovu svého nákupu zadejte emailovou adresu, která byla k nákupu použita:'''
issue_email_sent = '''Právě jsme vám zaslali email s odkazem na aktivaci vašeho produktu.'''
issue_or_digit = '''Nebo můžete zadat 6 místný kód, který jsme vám poslali:'''
issue_just_digit = '''Vložte 6 místný kód, který jsme vám poslali:'''
issue_i_have_a_code = '''(Klikněte zde, pokud již máte kód)'''
issue_i_have_a_key = '''(Klikněte zde, pokud již máte licenční klíč)'''
issue_key = '''Vložte svůj licenční klíč k Video Download Helperu:'''
landing_text1 = '''Stáhněte si jakékoli video z jakéhokoli webu, prostě to funguje!'''
landing_text2 = '''podporujeme více než 1000 webů'''
landing_text3 = '''Věří nám 7 miliónů uživatelů'''
landing_text4 = '''4.5 hvězdičky v obchodě s rozšířeními'''
landing_install_for_google = '''Instalace pro Chrome'''
landing_install_for_mozilla = '''Instalace pro Firefox'''
landing_install_for_microsoft = '''Instalace pro Edge'''
landing_feature1_title = '''HD stahování plnou rychlostí'''
landing_feature1_description = '''Stahujte videa ve vysokém rozlišení maximální rychlostí. Hrdě prohlašujeme, že máme nejrychlejší stahovací pohon ze všech tady.'''
landing_feature2_title = '''Archivace videí'''
landing_feature2_description = '''Archivujte svá oblíbená videa, abyste na nic nezapomněli.'''
landing_feature3_title = '''Podpora živého vysílání'''
landing_feature3_description = '''Vychutnejte si sledování živých strímů osvobozeni od omezení reálným časem.'''
landing_feature4_title = '''Stahování zvuku'''
landing_feature4_description = '''Vytáhněte zvukové stopy z videí, převeďte je na MP3 nebo podkasty pro snadný poslech.'''
premium_hero1 = '''Zaplaťte jednou, používejte navždy'''
premium_hero2 = '''Získejte doživotní licenci pro Vide Download Helper'''
premium_hero3 = '''Stahujte si jakákoli videa jak moc chcete, bez omezení.'''
welcome_text = '''Nyní už vám žádné video neuteče!'''
welcome_pin_message = '''Připnout ikonu rozšíření na lištu:'''
